"""Añadir orden de compra y posiciones

Revision ID: 361521707da1
Revises: eb398350e387
Create Date: 2025-07-30 12:18:42.538059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361521707da1'
down_revision = 'eb398350e387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llanta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orden_compra', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llanta', schema=None) as batch_op:
        batch_op.drop_column('orden_compra')

    # ### end Alembic commands ###
