"""Agregar modelos para mantenimiento

Revision ID: 507d0559cb8e
Revises: 361521707da1
Create Date: 2025-07-31 13:27:33.639654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507d0559cb8e'
down_revision = '361521707da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orden_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=True),
    sa.Column('falla_reportada', sa.Text(), nullable=False),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refaccion_utilizada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['orden_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refaccion_utilizada')
    op.drop_table('orden_trabajo')
    # ### end Alembic commands ###
