"""Migracion inicial para la version limpia

Revision ID: 7066d90c47fd
Revises: 
Create Date: 2025-08-04 09:05:11.834827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7066d90c47fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_economico', sa.String(length=80), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=True),
    sa.Column('conductor', sa.String(length=120), nullable=True),
    sa.Column('qr_id', sa.String(length=36), nullable=False),
    sa.Column('qr_code_b64', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('status_before_maintenance', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_economico'),
    sa.UniqueConstraint('placa'),
    sa.UniqueConstraint('qr_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_acceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('conductor_asignado', sa.String(length=120), nullable=True),
    sa.Column('photo_filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_salida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_acceso_id', sa.Integer(), nullable=False),
    sa.Column('llantas_estado', sa.String(length=10), nullable=True),
    sa.Column('llantas_obs', sa.Text(), nullable=True),
    sa.Column('llantas_foto', sa.String(length=255), nullable=True),
    sa.Column('luces_estado', sa.String(length=10), nullable=True),
    sa.Column('luces_obs', sa.Text(), nullable=True),
    sa.Column('luces_foto', sa.String(length=255), nullable=True),
    sa.Column('niveles_estado', sa.String(length=10), nullable=True),
    sa.Column('niveles_obs', sa.Text(), nullable=True),
    sa.Column('niveles_foto', sa.String(length=255), nullable=True),
    sa.Column('carroceria_estado', sa.String(length=10), nullable=True),
    sa.Column('carroceria_obs', sa.Text(), nullable=True),
    sa.Column('carroceria_foto', sa.String(length=255), nullable=True),
    sa.Column('observaciones_generales', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['registro_acceso_id'], ['registro_acceso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidencia_fotografica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_acceso_id', sa.Integer(), nullable=False),
    sa.Column('tipo_foto', sa.String(length=50), nullable=False),
    sa.Column('url_foto', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registro_acceso_id'], ['registro_acceso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidencia_fotografica')
    op.drop_table('checklist_salida')
    op.drop_table('registro_acceso')
    op.drop_table('audit_log')
    op.drop_table('vehiculos')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('operadores')
    # ### end Alembic commands ###
