"""Agregar modelos para control de llantas

Revision ID: eb398350e387
Revises: 
Create Date: 2025-07-30 11:16:09.103341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb398350e387'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llanta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dot_serial', sa.String(length=80), nullable=False, comment='Identificador único de la llanta'),
    sa.Column('marca', sa.String(length=80), nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=False),
    sa.Column('medida', sa.String(length=50), nullable=False),
    sa.Column('fecha_compra', sa.Date(), nullable=False),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('kilometraje_acumulado', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dot_serial')
    )
    op.create_table('posicion_eje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False, comment='Ej: DI, DD, TIEI, TIEE...'),
    sa.Column('descripcion', sa.String(length=100), nullable=False, comment='Ej: Delantera Izquierda, Trasera Izquierda Eje Interior...'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('montaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llanta_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('posicion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_montaje', sa.DateTime(), nullable=True),
    sa.Column('km_montaje', sa.Float(), nullable=False),
    sa.Column('fecha_desmontaje', sa.DateTime(), nullable=True),
    sa.Column('km_desmontaje', sa.Float(), nullable=True),
    sa.Column('motivo_desmontaje', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['llanta_id'], ['llanta.id'], ),
    sa.ForeignKeyConstraint(['posicion_id'], ['posicion_eje.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspeccion_llanta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('montaje_id', sa.Integer(), nullable=False),
    sa.Column('registro_acceso_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inspeccion', sa.DateTime(), nullable=True),
    sa.Column('presion_psi', sa.Integer(), nullable=False),
    sa.Column('profundidad_mm', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('foto_dano', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['montaje_id'], ['montaje.id'], ),
    sa.ForeignKeyConstraint(['registro_acceso_id'], ['registro_acceso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspeccion_llanta')
    op.drop_table('montaje')
    op.drop_table('posicion_eje')
    op.drop_table('llanta')
    # ### end Alembic commands ###
